// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Uni.Scan.Domain.Contracts;

namespace Uni.Scan.Domain.Entities
{
    public partial class LogisticArea  
    {
        [Key]
        public string ObjectID { get; set; }
        public string LogisticAreaUUID { get; set; }
        public string LogisticAreaID { get; set; }
        public string InventoryManagedLocationID { get; set; }
        public string InventoryManagedLocationUUID { get; set; }
        public string SiteID { get; set; }
        public string SiteUUID { get; set; }
        public string TypeCode { get; set; }
        public string TypeCodeText { get; set; }

        public bool InventoryManagedLocationIndicator { get; set; }
        public string SiteName { get; set; }
        public string LifeCycleStatusCode { get; set; }
        public string LifeCycleStatusCodeText { get; set; }
        public string ParentLocationUUID { get; set; }
    }
}