// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Uni.Scan.Domain.Contracts;
using Uni.Scan.Shared.Enums;

namespace Uni.Scan.Domain.Entities
{
    public class LogisticTaskLabel : AuditableEntity<int>
    {
        public string TaskId { get; set; }
        public int LineItemID { get; set; }
        public string Title { get; set; }
        public LabelType Type { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal PlanQuantity { get; set; }
        public string IdentifiedStock { get; set; }
        public string SerialStock { get; set; }
        public int Status { get; set; }
        public decimal QuatityOnLabel { get; set; }  
        public string QuatityUnite { get; set; }
        public DateTime ProductionDate { get; set; }
        public DateTime ExpirationDate { get; set; }
        public string ExternalID { get; set; }
        public string ProductSpecification { get; set; }
        public string GTIN { get; set; }
        public string PackageID { get; set; }
        public string TransferOrdre { get; set; }
        public string ProductionOrdre { get; set; }
        public string FabricationOrdre { get; set; }
        public string SupplierIdentifiedStock { get; set; }
        public string Tare { get; set; }
        public string Comment { get; set; }
        public int NbrEtiquettes { get; set; }
        public int Duplicata { get; set; }
        public virtual LogisticTask Task { get; set; }
    }
}