// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Uni.Scan.Domain.Entities
{
    public partial class Material
    {
        [Key]
        public string ObjectID { get; set; }
        public string ProductID { get; set; }
        public string Description_KUT { get; set; }
        public string ProductValuationLevelTypeCode { get; set; }
        public string ProductValuationLevelTypeCodeText { get; set; }
        public string SerialIdentifierAssignmentProfileCode { get; set; }
        public string SerialIdentifierAssignmentProfileCodeText { get; set; }
        public string InternalID { get; set; }
        public string ProductIdentifierTypeCode { get; set; }
        public string ProductIdentifierTypeCodeText { get; set; }
        public string ProductTypeCode { get; set; }
        public string ProductTypeCodeText { get; set; }
        public string BaseMeasureUnitCode { get; set; }
    }
}